Edit printing of age and fix bug in printing graph
According to assignment all age groups have to be printed even if there
is 0.
When the parameter of -s is given, it can't be rounded.

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -55,11 +55,13 @@ awk_histogram()
   else
     awk -F ':' -v s="$S_FLAG" 'BEGIN {max=0;} {
       if (max<$2) {max=$2;} a[NR] = $1; value[NR] = $2;}
-      END { tmp=(int(max / s));
-            for (i=1; i<=NR; i++) {constant=(int(value[i] / tmp));
-            printf("%s:", a[i]);
-            if (constant) {printf(" ")}; 
-            while (constant) { printf("#"); constant--} printf("\n");}}'
+      END { tmp=(max / s);
+            for (i=1; i<=NR; i++) {
+              constant=(int(value[i] / tmp));
+              printf("%s:", a[i]);
+              if (constant) {printf(" ");} 
+              while (constant--) {printf("#"); constant;} 
+              printf("\n");}  }'
   fi
 }
 
@@ -123,7 +125,7 @@ while [ $# -gt 0 ]; do
 					  exit 1
 					fi
 				else
-					>&2 echo "error: Filter moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
+					>&2 echo "error: Filter -b moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
 					exit 1
 				fi
 			fi
@@ -141,7 +143,7 @@ while [ $# -gt 0 ]; do
 	          exit 1
 	        fi
 	      else
-	        >&2 echo "error: Filter moze byt pouzity len 1-krat. a na prvej pozicii (viz. -h)."
+	        >&2 echo "error: Filter -g moze byt pouzity len 1-krat. a na prvej pozicii (viz. -h)."
 	        exit 1
 	      fi
 	    fi
@@ -149,7 +151,7 @@ while [ $# -gt 0 ]; do
 	    ;;
 	  -s)
 	    if [ -n "$S_FLAG" ] || ! [ "$ARG_INDEX" = "1" ]; then
-	      >&2 echo "error: Filter moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
+	      >&2 echo "error: Filter -s moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
         exit 1
 	    else
 	      # no need to check whether the next argument exists
@@ -231,7 +233,11 @@ if ! [ $COMMAND = "PROCESSED" ]; then
   OUTPUT=$( echo "$LOG_FILES"  | sed -r 's/\s+//g' | awk_filter |
     case $COMMAND in
       age)
-        awk -F ',' 'NR>1 {
+        awk -F ',' 'BEGIN  {
+          a[">105  "] = a["96-105"] = a["86-95 "] = a["76-85 "] = 0;
+          a["66-75 "] = a["56-65 "] = a["46-55 "] = a["36-45 "] = 0;
+          a["26-35 "] = a["16-25 "] = a["6-15  "] = a["0-5   "] = 0;} 
+          NR>1 {
           if ($3 > 105)       {a[">105  "]++;}
           else if ($3 > 95)   {a["96-105"]++;}
           else if ($3 > 85)   {a["86-95 "]++;}
@@ -250,7 +256,7 @@ if ! [ $COMMAND = "PROCESSED" ]; then
         ;;
       gender)
         awk -F ',' 'NR>1 {if ($4 != "") {a[$4]++;} else {a["None"]++;}} 
-        END{for(i in a) {print i ": " a[i];}}' | sort -V |
+        END     {for(i in a) {print i ": " a[i];}}' | sort -V |
         awk -F ':' '{if ($1 != "None") {print $0;} else {a = $0;}} END {print a}'
         ;;
       daily)
