Add parsing -g argument

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -68,6 +68,23 @@ while [ $# -gt 0 ]; do
 				fi
 			fi
 			;;
+	  -g)
+	    if [ $# -lt 1 ]; then
+	      echo "error: Chybajuci argument k filtru -g"
+	      exit 1
+	    else
+	      if [ "$FILTER_GENDER" = "off" ]; then
+	        FILTER_GENDER=$1
+	        if ! [[ $FILTER_GENDER =~ ^[M]|[Z]$ ]]; then
+	          echo "error: Parameter pohlavia moze byt len M alebo Z."
+	          exit 1
+	        fi
+	      else
+	        echo "error: Filter moze byt pouzity len 1-krat."
+	        exit 1
+	      fi
+	    fi
+	    ;;
 	  -w)
 	    if [ $# -lt 1 ]; then
 	      echo "error: Chybajuci argument k filtru -w."
