Update printing errors to stderr

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -39,18 +39,11 @@ awk_filter()
   echo "id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs"
 
   awk -F ','  -v filter_after="$FILTER_AFTER" -v filter_before="$FILTER_BEFORE" \
-              -v filter_gender="$FILTER_GENDER" -v rgx_dt="${_regex_date}" -v rgx_int="${_regex_integer}" '{
-    if ((NF <= 9 && NF > 1) && ($2 ~ rgx_dt || $2 == "") && $2 >= filter_after && $2 <= filter_before \
-      && $4 == (filter_gender ? filter_gender : $4 ) && $3 ~ rgx_int) {print $0}}'
-}
-
-awk_invalid()
-{
- awk -F ',' -v filter_after="$FILTER_AFTER" -v filter_before="$FILTER_BEFORE" -v filter_gender="$FILTER_GENDER" \
-            -v rgx_dt="${_regex_date}" -v rgx_int="${_regex_integer}" '{
-    if (NF <= 9 && NF>1 && $2 >= filter_after && $2 <= filter_before && $4 == (filter_gender ? filter_gender : $4 ))  {
-      if (!($2 ~ rgx_dt || $2 == ""))       {print "Invalid date: " $0;}
-      else if (!($3 ~ rgx_int || $2 == "")) {print "Invalid age: " $0}}}'
+              -v filter_gender="$FILTER_GENDER" -v rgx_dt="${_regex_date}" -v rgx_int="${_regex_integer}" 'NR>1 {
+    if (!($2 ~ rgx_dt) && $2 != "datum")           {print "Invalid date: " $0 | "cat 1>&2";}
+    else if (!($3 ~ rgx_int) && $3 != "vek")       {print "Invalid age: " $0 | "cat 1>&2";}
+    else if ((NF <= 9 && NF > 1) && $2 >= filter_after && $2 <= filter_before && \
+      $4 == (filter_gender ? filter_gender : $4))  {print $0}}'
 }
 
 awk_histogram()
@@ -102,17 +95,17 @@ while [ $# -gt 0 ]; do
 	case $key in
 		-a|--after)
 			if [ $# -lt 1 ]; then
-				echo "error: Chybajuci argument k filtru -a"
+				>&2 echo "error: Chybajuci argument k filtru -a"
 				exit 1
 			else
 				if [ -z "$FILTER_AFTER" ] && [ "$ARG_INDEX" = "1" ]; then
 					FILTER_AFTER=$1
 					if ! echo "$FILTER_AFTER" | grep -qE "$_regex_date"; then
-            echo "error: Datum musi byt vo formate YYYY-MM-DDD"
+            >&2 echo "error: Datum musi byt vo formate YYYY-MM-DDD"
             exit 1
           fi
 				else
-					echo "error: Filter -a moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
+					>&2 echo "error: Filter -a moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
 					exit 1
 				fi
 			fi
@@ -120,17 +113,17 @@ while [ $# -gt 0 ]; do
 			;;
 		-b|--before)
 			if [ $# -lt 1 ]; then
-				echo "error: Chybajuci argument k filtru -b"
+				>&2 echo "error: Chybajuci argument k filtru -b"
 				exit 1
 			else
 				if [ "$FILTER_BEFORE" = "9999-12-31" ] && [ "$ARG_INDEX" = "1" ]; then
 					FILTER_BEFORE=$1
 					if ! echo "$FILTER_BEFORE" | grep -Eq "$_regex_date"; then
-					  echo "error: Datum musi byt vo formate YYYY-MM-DD"
+					  >&2 echo "error: Datum musi byt vo formate YYYY-MM-DD"
 					  exit 1
 					fi
 				else
-					echo "error: Filter moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
+					>&2 echo "error: Filter moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
 					exit 1
 				fi
 			fi
@@ -138,17 +131,17 @@ while [ $# -gt 0 ]; do
 			;;
 	  -g|--gender)
 	    if [ $# -lt 1 ]; then
-	      echo "error: Chybajuci argument k filtru -g"
+	      >&2  echo "error: Chybajuci argument k filtru -g"
 	      exit 1
 	    else
 	      if [ -z "$FILTER_GENDER" ] && [ "$ARG_INDEX" = "1" ]; then
 	        FILTER_GENDER=$1
 	        if ! echo "$FILTER_GENDER" | grep -qE '^[M]$|^[Z]$'; then
-	          echo "error: Parameter pohlavia moze byt len M alebo Z."
+	          >&2 echo "error: Parameter pohlavia moze byt len M alebo Z."
 	          exit 1
 	        fi
 	      else
-	        echo "error: Filter moze byt pouzity len 1-krat. a na prvej pozicii (viz. -h)."
+	        >&2 echo "error: Filter moze byt pouzity len 1-krat. a na prvej pozicii (viz. -h)."
 	        exit 1
 	      fi
 	    fi
@@ -156,7 +149,7 @@ while [ $# -gt 0 ]; do
 	    ;;
 	  -s)
 	    if [ -n "$S_FLAG" ] || ! [ "$ARG_INDEX" = "1" ]; then
-	      echo "error: Filter moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
+	      >&2 echo "error: Filter moze byt pouzity len 1-krat a na prvej pozicii (viz. -h)."
         exit 1
 	    else
 	      # no need to check whether the next argument exists
@@ -165,7 +158,7 @@ while [ $# -gt 0 ]; do
 	        S_FLAG="default"
 	      else
 	        if ! echo "$1"  | grep -qE '^[1-9][0-9]*$'; then
-	          echo "error: Parameter sirky moze byt len cele kladne cislo vacsie ako 0."
+	          >&2 echo "error: Parameter sirky moze byt len cele kladne cislo vacsie ako 0."
             exit 1
           fi
 	        S_FLAG=$1
@@ -182,7 +175,7 @@ while [ $# -gt 0 ]; do
 	      COMMAND=$key
         ARG_INDEX="2"
 	    else
-	      echo "error: Prikaz moze byt uvedeny len raz a na druhej pozicii (viz. -h)."
+	      >&2 echo "error: Prikaz moze byt uvedeny len raz a na druhej pozicii (viz. -h)."
 	      exit 1
 	    fi
 	    ;;
@@ -199,7 +192,7 @@ while [ $# -gt 0 ]; do
       ARG_INDEX="3"
       ;;
 	  *)
-	    printf "error: Prikaz %s je neznamy. Precitajte si manual!\n" "$key"
+	    >&2 printf "error: Prikaz %s je neznamy. Precitajte si manual!\n" "$key"
 	    print_help
 	    exit 1
 	    ;;
@@ -307,6 +300,3 @@ if ! [ $COMMAND = "PROCESSED" ]; then
     echo "$OUTPUT"
   fi
 fi
-
-# in the end output all invalid lines by doing the same process again
-echo "$LOG_FILES" | sed -r 's/\s+//g' | awk_invalid
