Add function for graphs and comment out parsing -s argument

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -40,10 +40,29 @@ awk_filter()
   fi
 }
 
+awk_histogram()
+{
+  if [ $S_FLAG="on" ]; then
+    awk -F ':' -v width="$S_HISTOGRAM" '{
+    constant=(int($2 / width)); printf("%s: ", $1); while (constant) { printf("#"); constant--} printf("\n");}'
+  else
+    awk -F ':' -v s="$S" '
+      BEGIN {max=0;}
+      {      if (max<$2) {max=$2;} a[NR] = $1; value[NR] = $2;}
+      END { tmp=(int(max / s));
+            for (i=1; i<=NR; i++) {constant=(int(value[i] / tmp));
+            printf("%s: ", a[i]);
+            while (constant) { printf("#"); constant--} printf("\n");}}'
+  fi
+}
+
 FILTER_AFTER=""
 FILTER_BEFORE="9999-12-31"
 FILTER_GENDER=""
-FILTER_WIDTH="off"
+
+S_FLAG="off"
+S_HISTOGRAM=""
+S=""
 
 COMMAND=off
 
@@ -51,7 +70,7 @@ GZ_LOG_FILES=""
 LOG_FILES=""
 
 _regex_date='^[0-9]{4}[-](0[1-9]|1[0-2])[-](0[1-9]|[1-2][0-9]|3[0-1])$'
-_regex_age='^\b[0-9]+\b$'
+_regex_age='^[0-9]+$'
 
 # parsing filters
 while [ $# -gt 0 ]; do
@@ -114,24 +133,24 @@ while [ $# -gt 0 ]; do
 	    fi
 	    shift
 	    ;;
-	  -w)
-	    if [ $# -lt 1 ]; then
-	      echo "error: Chybajuci argument k filtru -w."
-	      exit 1
-	    else
-	      if [ "$FILTER_WIDTH" = "off" ]; then
-	        FILTER_WIDTH=$1
-	        if ! [[ $FILTER_WIDTH =~ ^[0-9]+$ ]]; then
-	          echo "error: Parameter sirky musi byt cele kladne cislo."
-	          exit 1
-	        fi
-	      else
-	        echo "error: Filter moze byt pouzity len 1-krat."
-	        exit 1
-	      fi
-	    fi
-	    shift
-	    ;;
+	  -s)
+	    #if [ $S_FLAG="off" ]; then
+	    #  S_FLAG="on"
+	    #  if [ $# -lt 1 ]; then
+      #    S_HISTOGRAM=100000
+      #  else
+      #    S=$1
+      #    if ! [[ $S =~ ^[0-9]+$ ]]; then
+      #      echo "error: Parameter sirky moze byt len cele kladne cislo."
+      #      exit 1
+      #    fi
+      #  fi
+	    #else
+      #  echo "error: Filter moze byt pouzity len 1-krat."
+      #  exit 1
+      #fi
+      #shift
+      #;;
 	  infected|merge|gender|age|daily|monthly|yearly|countries|districts|regions)
 	    if [ "$COMMAND" = "off" ]; then
 	      COMMAND=$key
