Support optional argument of -s argument

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -63,7 +63,7 @@ awk_histogram()
   if [[ $S_FLAG = "default" ]]; then
     awk -F ':' -v width="$WIDTH" '{
     constant=(int($2 / width)); printf("%s: ", $1); while (constant) { printf("#"); constant--} printf("\n");}'
-  elif ! [[ -z $S_FLAG  ]]; then
+  else
     awk -F ':' -v s="$S_FLAG" '
       BEGIN {max=0;}
       {      if (max<$2) {max=$2;} a[NR] = $1; value[NR] = $2;}
@@ -102,25 +102,25 @@ while [ $# -gt 0 ]; do
 	key=$1
 	shift
 	case $key in
-		-a|-after)
+		-a|--after)
 			if [ $# -lt 1 ]; then
 				echo "error: Chybajuci argument k filtru -a"
 				exit 1
 			else
-				if [ -z $FILTER_AFTER ]; then
+				if [[ -z $FILTER_AFTER ]]; then
 					FILTER_AFTER=$1
 					if ! [[ $FILTER_AFTER =~ ${_regex_date} ]]; then
             echo "error: Datum musi byt vo formate YYYY-MM-DDD"
             exit 1
           fi
 				else
-					echo "error: Filter moze byt pouzity len 1-krat."
+					echo "error: Filter -a moze byt pouzity len 1-krat."
 					exit 1
 				fi
 			fi
 			shift
 			;;
-		-b|-before)
+		-b|--before)
 			if [ $# -lt 1 ]; then
 				echo "error: Chybajuci argument k filtru -b"
 				exit 1
@@ -134,13 +134,13 @@ while [ $# -gt 0 ]; do
 					  exit 1
 					fi
 				else
-					echo "error: Filter moze byt pouzity len 1-krat."
+					echo "error: Filter -b moze byt pouzity len 1-krat."
 					exit 1
 				fi
 			fi
 			shift
 			;;
-	  -g)
+	  -g|--gender)
 	    if [ $# -lt 1 ]; then
 	      echo "error: Chybajuci argument k filtru -g"
 	      exit 1
@@ -163,29 +163,31 @@ while [ $# -gt 0 ]; do
 	      echo "error: Filter -s moze byt pouzity len 1-krat."
         exit 1
 	    else
-	      if [[ $# -lt 1 ]]; then
+	      # no need to check whether the next argument exists
+	      # check just whether there's any number and then check its validity
+	      if ! [[ $1 =~ ^[+-]?[0-9]+([.][0-9]+)?$ ]]; then
 	        S_FLAG="default"
 	      else
-	        if ! [[ $1 =~ ${_regex_integer} ]]; then #^[1-9][0-9]*$
+	        if ! [[ $1 =~ ^[1-9][0-9]*$ ]]; then
 	          echo "error: Parameter sirky moze byt len cele kladne cislo vacsie ako 0."
             exit 1
           fi
 	        S_FLAG=$1
+	        shift
 	      fi
 	    fi
-	    shift
+	    ;;
+	  -h|--help)
+	    print_help
+	    break
 	    ;;
 	  infected|merge|gender|age|daily|monthly|yearly|countries|districts|regions)
-	    if [ "$COMMAND" = "off" ]; then
+	    if [[ "$COMMAND" = "off" ]]; then
 	      COMMAND=$key
 	    else
 	      echo "error: Prikaz moze byt uvedeny len raz."
 	      exit 1
 	    fi
-	    ;;
-	  -h)
-	    print_help
-	    break
 	    ;;
 	  *.gz)
 	    LOG_FILES=$( gzip -d -c $key )
@@ -222,6 +224,8 @@ case $COMMAND in
     ;;
 esac
 
+
+
 if ! [[ $COMMAND = "PROCESSED" ]]; then
   OUTPUT=$( echo "$LOG_FILES"  | sed -r 's/\s+//g' | awk_filter |
     case $COMMAND in
@@ -248,7 +252,6 @@ if ! [[ $COMMAND = "PROCESSED" ]]; then
         awk -F ',' 'NR>1 {a[$4]++} END{for(i in a) print i ": " a[i]}'
         ;;
       daily)
-        WIDTH=500
         awk_daily | sort
         ;;
       monthly)
@@ -282,12 +285,23 @@ if ! [[ $COMMAND = "PROCESSED" ]]; then
         ;;
     esac
   )
-  if [[ S_FLAG > 0 ]]; then
+  case $COMMAND in
+    age)        WIDTH=10000;;
+    gender)     WIDTH=100000;;
+    daily)      WIDTH=500;;
+    monthly)    WIDTH=10000;;
+    yearly)     WIDTH=100000;;
+    countries)  WIDTH=100;;
+    districts)  WIDTH=1000;;
+    regions)    WIDTH=10000;;
+  esac
+
+  if ! [[ -z "$S_FLAG" ]]; then
     echo "$OUTPUT" | awk_histogram
   else
     echo "$OUTPUT"
   fi
 fi
 
-echo "$LOG_FILES" | sed -r 's/\s+//g' | awk_invalid
 # in the end output all invalid lines by doing the same process again
+echo "$LOG_FILES" | sed -r 's/\s+//g' | awk_invalid
