Add parsing -w argument

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -29,6 +29,7 @@ FILTER_BEFORE=off
 FILTER_GENDER=off
 FILTER_WIDTH=off
 
+# parsing filters
 while [ $# -gt 0 ]; do
 	key=$1
 	shift
@@ -67,7 +68,24 @@ while [ $# -gt 0 ]; do
 				fi
 			fi
 			;;
-	esac	
+	  -w)
+	    if [ $# -lt 1 ]; then
+	      echo "error: Chybajuci argument k filtru -w."
+	      exit 1
+	    else
+	      if [ "$FILTER_WIDTH" = "off" ]; then
+	        FILTER_WIDTH=$1
+	        if ! [[ $FILTER_WIDTH =~ ^[0-9]+$ ]]; then
+	          echo "error: Parameter sirky musi byt cele kladne cislo."
+	          exit 1
+	        fi
+	      else
+	        echo "error: Filter moze byt pouzity len 1-krat."
+	        exit 1
+	      fi
+	    fi
+	    ;;
+	esac
 done
 
 # make sure the date is in correct format
